spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/yl?useSSL=true&serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
#开启驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: false