spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://39.105.68.212:3306/yl?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
#开启驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: false